# Generated by Django 2.0.6 on 2018-07-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_sensitive_only',
            field=models.BooleanField(default=False),
        ),
    ]
