# Generated by Django 2.0.6 on 2018-06-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=3)),
                ('asx_date', models.DateTimeField()),
                ('price_sensitive', models.BooleanField(default=False)),
                ('headline', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=140)),
                ('pages', models.IntegerField()),
                ('filesize', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asx_code', models.CharField(max_length=10)),
                ('asx_code_aka', models.CharField(max_length=3)),
                ('company_name', models.CharField(max_length=140)),
                ('gics_industry_group', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('listing_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.Company'),
        ),
    ]
