# Generated by Django 2.0.6 on 2018-06-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['url'], name='url_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['asx_code_aka'], name='asx_code_aka_idx'),
        ),
    ]
